### ISSUE TITLE
demoAdapterPage2.page doesn't exist

### ISSUE THREAD

**Issue by mascot4m** [developerforce/open-cti-demo-adapter#21]
The OpenCTI.callCenter refers in item `CTI Adapter URL2` to `demoAdapterPage2` , which is not in repo.
Caused error after installation. Simple fix - I changed the `demoAdapterPage2` to `demoAdapterPage`.

**Comment by dlouvton** [comment]
thanks! i updated the repo with demoAdapterPage instead demoAdapterPage2.

**Comment by Ou2sYB** [comment]
Hi , 
Click Edit next to the Demo Call Center Adapter and make sure that the CTI Adapter URL points to the relative or absolute path of the Visualforce page called managedPage. For example, the following URLs are valid:
/apex/demoAdapterPage
/apex/namespace__demoAdapterPage (when using a managed package)
https://<myDomain>.my.salesforce.com/apex/demoAdapterPage (when using My Domain)
https://<namespace-dev-ed>.my.salesforce.com/apex/namespace_demoAdapterPage (when using a managed package and My Domain)
If your Adapter URL doesn’t work, use the Chrome Inspector tool to troubleshoot the problem. You might see this error: “Blocked a frame with origin “https://<myDomain>.my.salesforce.com” from accessing a cross-origin fame.” This error lets you know that you need to use an absolute URL that starts with “https://<myDomain>.my.salesforce.com” instead of a relative one.
